<?php
/**
 * ComplianceJobStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.60
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * ComplianceJobStatus Class Doc Comment
 *
 * @category Class
 * @description Status of a compliance job.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ComplianceJobStatus
{
    /**
     * Possible values of this enum
     */
    const CREATED = 'created';
const IN_PROGRESS = 'in_progress';
const FAILED = 'failed';
const COMPLETE = 'complete';
const EXPIRED = 'expired';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CREATED,
self::IN_PROGRESS,
self::FAILED,
self::COMPLETE,
self::EXPIRED,        ];
    }
}
