<?php
/**
 * ReplySettings
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.60
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * ReplySettings Class Doc Comment
 *
 * @category Class
 * @description Shows who can reply a Tweet. Fields returned are everyone, mentioned_users, and following.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReplySettings
{
    /**
     * Possible values of this enum
     */
    const EVERYONE = 'everyone';
const MENTIONED_USERS = 'mentionedUsers';
const FOLLOWING = 'following';
const OTHER = 'other';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EVERYONE,
self::MENTIONED_USERS,
self::FOLLOWING,
self::OTHER,        ];
    }
}
