<?php
/**
 * TweetCreateRequestReply
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.60
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * TweetCreateRequestReply Class Doc Comment
 *
 * @category Class
 * @description Tweet information of the Tweet being replied to.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TweetCreateRequestReply implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'TweetCreateRequest_reply';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'exclude_reply_user_ids' => '\Swagger\Client\Model\UserId[]',
'in_reply_to_tweet_id' => '\Swagger\Client\Model\TweetId'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'exclude_reply_user_ids' => null,
'in_reply_to_tweet_id' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'exclude_reply_user_ids' => 'exclude_reply_user_ids',
'in_reply_to_tweet_id' => 'in_reply_to_tweet_id'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'exclude_reply_user_ids' => 'setExcludeReplyUserIds',
'in_reply_to_tweet_id' => 'setInReplyToTweetId'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'exclude_reply_user_ids' => 'getExcludeReplyUserIds',
'in_reply_to_tweet_id' => 'getInReplyToTweetId'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['exclude_reply_user_ids'] = isset($data['exclude_reply_user_ids']) ? $data['exclude_reply_user_ids'] : null;
        $this->container['in_reply_to_tweet_id'] = isset($data['in_reply_to_tweet_id']) ? $data['in_reply_to_tweet_id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['in_reply_to_tweet_id'] === null) {
            $invalidProperties[] = "'in_reply_to_tweet_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets exclude_reply_user_ids
     *
     * @return \Swagger\Client\Model\UserId[]
     */
    public function getExcludeReplyUserIds()
    {
        return $this->container['exclude_reply_user_ids'];
    }

    /**
     * Sets exclude_reply_user_ids
     *
     * @param \Swagger\Client\Model\UserId[] $exclude_reply_user_ids A list of User Ids to be excluded from the reply Tweet.
     *
     * @return $this
     */
    public function setExcludeReplyUserIds($exclude_reply_user_ids)
    {
        $this->container['exclude_reply_user_ids'] = $exclude_reply_user_ids;

        return $this;
    }

    /**
     * Gets in_reply_to_tweet_id
     *
     * @return \Swagger\Client\Model\TweetId
     */
    public function getInReplyToTweetId()
    {
        return $this->container['in_reply_to_tweet_id'];
    }

    /**
     * Sets in_reply_to_tweet_id
     *
     * @param \Swagger\Client\Model\TweetId $in_reply_to_tweet_id in_reply_to_tweet_id
     *
     * @return $this
     */
    public function setInReplyToTweetId($in_reply_to_tweet_id)
    {
        $this->container['in_reply_to_tweet_id'] = $in_reply_to_tweet_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange] 
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange] 
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
