<?php
/**
 * TweetNotice
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.60
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * TweetNotice Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TweetNotice implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'TweetNotice';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'application' => 'string',
'details' => 'string',
'event_at' => '\DateTime',
'event_type' => 'string',
'extended_details_url' => 'string',
'label_title' => 'string',
'tweet' => '\Swagger\Client\Model\TweetComplianceSchemaTweet'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'application' => null,
'details' => null,
'event_at' => 'date-time',
'event_type' => null,
'extended_details_url' => null,
'label_title' => null,
'tweet' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'application' => 'application',
'details' => 'details',
'event_at' => 'event_at',
'event_type' => 'event_type',
'extended_details_url' => 'extended_details_url',
'label_title' => 'label_title',
'tweet' => 'tweet'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'application' => 'setApplication',
'details' => 'setDetails',
'event_at' => 'setEventAt',
'event_type' => 'setEventType',
'extended_details_url' => 'setExtendedDetailsUrl',
'label_title' => 'setLabelTitle',
'tweet' => 'setTweet'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'application' => 'getApplication',
'details' => 'getDetails',
'event_at' => 'getEventAt',
'event_type' => 'getEventType',
'extended_details_url' => 'getExtendedDetailsUrl',
'label_title' => 'getLabelTitle',
'tweet' => 'getTweet'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['application'] = isset($data['application']) ? $data['application'] : null;
        $this->container['details'] = isset($data['details']) ? $data['details'] : null;
        $this->container['event_at'] = isset($data['event_at']) ? $data['event_at'] : null;
        $this->container['event_type'] = isset($data['event_type']) ? $data['event_type'] : null;
        $this->container['extended_details_url'] = isset($data['extended_details_url']) ? $data['extended_details_url'] : null;
        $this->container['label_title'] = isset($data['label_title']) ? $data['label_title'] : null;
        $this->container['tweet'] = isset($data['tweet']) ? $data['tweet'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['application'] === null) {
            $invalidProperties[] = "'application' can't be null";
        }
        if ($this->container['event_at'] === null) {
            $invalidProperties[] = "'event_at' can't be null";
        }
        if ($this->container['event_type'] === null) {
            $invalidProperties[] = "'event_type' can't be null";
        }
        if ($this->container['tweet'] === null) {
            $invalidProperties[] = "'tweet' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets application
     *
     * @return string
     */
    public function getApplication()
    {
        return $this->container['application'];
    }

    /**
     * Sets application
     *
     * @param string $application If the label is being applied or removed. Possible values are ‘apply’ or ‘remove’.
     *
     * @return $this
     */
    public function setApplication($application)
    {
        $this->container['application'] = $application;

        return $this;
    }

    /**
     * Gets details
     *
     * @return string
     */
    public function getDetails()
    {
        return $this->container['details'];
    }

    /**
     * Sets details
     *
     * @param string $details Information shown on the Tweet label
     *
     * @return $this
     */
    public function setDetails($details)
    {
        $this->container['details'] = $details;

        return $this;
    }

    /**
     * Gets event_at
     *
     * @return \DateTime
     */
    public function getEventAt()
    {
        return $this->container['event_at'];
    }

    /**
     * Sets event_at
     *
     * @param \DateTime $event_at Event time.
     *
     * @return $this
     */
    public function setEventAt($event_at)
    {
        $this->container['event_at'] = $event_at;

        return $this;
    }

    /**
     * Gets event_type
     *
     * @return string
     */
    public function getEventType()
    {
        return $this->container['event_type'];
    }

    /**
     * Sets event_type
     *
     * @param string $event_type The type of label on the Tweet
     *
     * @return $this
     */
    public function setEventType($event_type)
    {
        $this->container['event_type'] = $event_type;

        return $this;
    }

    /**
     * Gets extended_details_url
     *
     * @return string
     */
    public function getExtendedDetailsUrl()
    {
        return $this->container['extended_details_url'];
    }

    /**
     * Sets extended_details_url
     *
     * @param string $extended_details_url Link to more information about this kind of label
     *
     * @return $this
     */
    public function setExtendedDetailsUrl($extended_details_url)
    {
        $this->container['extended_details_url'] = $extended_details_url;

        return $this;
    }

    /**
     * Gets label_title
     *
     * @return string
     */
    public function getLabelTitle()
    {
        return $this->container['label_title'];
    }

    /**
     * Sets label_title
     *
     * @param string $label_title Title/header of the Tweet label
     *
     * @return $this
     */
    public function setLabelTitle($label_title)
    {
        $this->container['label_title'] = $label_title;

        return $this;
    }

    /**
     * Gets tweet
     *
     * @return \Swagger\Client\Model\TweetComplianceSchemaTweet
     */
    public function getTweet()
    {
        return $this->container['tweet'];
    }

    /**
     * Sets tweet
     *
     * @param \Swagger\Client\Model\TweetComplianceSchemaTweet $tweet tweet
     *
     * @return $this
     */
    public function setTweet($tweet)
    {
        $this->container['tweet'] = $tweet;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange] 
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange] 
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
