<?php
/**
 * TweetEditComplianceObjectSchema
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.60
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * TweetEditComplianceObjectSchema Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TweetEditComplianceObjectSchema implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'TweetEditComplianceObjectSchema';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'edit_tweet_ids' => '\Swagger\Client\Model\TweetId[]',
'event_at' => '\DateTime',
'initial_tweet_id' => '\Swagger\Client\Model\TweetId',
'tweet' => '\Swagger\Client\Model\DmEventReferencedTweets'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'edit_tweet_ids' => null,
'event_at' => 'date-time',
'initial_tweet_id' => null,
'tweet' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'edit_tweet_ids' => 'edit_tweet_ids',
'event_at' => 'event_at',
'initial_tweet_id' => 'initial_tweet_id',
'tweet' => 'tweet'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'edit_tweet_ids' => 'setEditTweetIds',
'event_at' => 'setEventAt',
'initial_tweet_id' => 'setInitialTweetId',
'tweet' => 'setTweet'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'edit_tweet_ids' => 'getEditTweetIds',
'event_at' => 'getEventAt',
'initial_tweet_id' => 'getInitialTweetId',
'tweet' => 'getTweet'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['edit_tweet_ids'] = isset($data['edit_tweet_ids']) ? $data['edit_tweet_ids'] : null;
        $this->container['event_at'] = isset($data['event_at']) ? $data['event_at'] : null;
        $this->container['initial_tweet_id'] = isset($data['initial_tweet_id']) ? $data['initial_tweet_id'] : null;
        $this->container['tweet'] = isset($data['tweet']) ? $data['tweet'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['edit_tweet_ids'] === null) {
            $invalidProperties[] = "'edit_tweet_ids' can't be null";
        }
        if ($this->container['event_at'] === null) {
            $invalidProperties[] = "'event_at' can't be null";
        }
        if ($this->container['initial_tweet_id'] === null) {
            $invalidProperties[] = "'initial_tweet_id' can't be null";
        }
        if ($this->container['tweet'] === null) {
            $invalidProperties[] = "'tweet' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets edit_tweet_ids
     *
     * @return \Swagger\Client\Model\TweetId[]
     */
    public function getEditTweetIds()
    {
        return $this->container['edit_tweet_ids'];
    }

    /**
     * Sets edit_tweet_ids
     *
     * @param \Swagger\Client\Model\TweetId[] $edit_tweet_ids edit_tweet_ids
     *
     * @return $this
     */
    public function setEditTweetIds($edit_tweet_ids)
    {
        $this->container['edit_tweet_ids'] = $edit_tweet_ids;

        return $this;
    }

    /**
     * Gets event_at
     *
     * @return \DateTime
     */
    public function getEventAt()
    {
        return $this->container['event_at'];
    }

    /**
     * Sets event_at
     *
     * @param \DateTime $event_at Event time.
     *
     * @return $this
     */
    public function setEventAt($event_at)
    {
        $this->container['event_at'] = $event_at;

        return $this;
    }

    /**
     * Gets initial_tweet_id
     *
     * @return \Swagger\Client\Model\TweetId
     */
    public function getInitialTweetId()
    {
        return $this->container['initial_tweet_id'];
    }

    /**
     * Sets initial_tweet_id
     *
     * @param \Swagger\Client\Model\TweetId $initial_tweet_id initial_tweet_id
     *
     * @return $this
     */
    public function setInitialTweetId($initial_tweet_id)
    {
        $this->container['initial_tweet_id'] = $initial_tweet_id;

        return $this;
    }

    /**
     * Gets tweet
     *
     * @return \Swagger\Client\Model\DmEventReferencedTweets
     */
    public function getTweet()
    {
        return $this->container['tweet'];
    }

    /**
     * Sets tweet
     *
     * @param \Swagger\Client\Model\DmEventReferencedTweets $tweet tweet
     *
     * @return $this
     */
    public function setTweet($tweet)
    {
        $this->container['tweet'] = $tweet;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange] 
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange] 
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
