<?php
/**
 * FullTextEntitiesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.60
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FullTextEntitiesTest Class Doc Comment
 *
 * @category    Class
 * @description FullTextEntities
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FullTextEntitiesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FullTextEntities"
     */
    public function testFullTextEntities()
    {
    }

    /**
     * Test attribute "annotations"
     */
    public function testPropertyAnnotations()
    {
    }

    /**
     * Test attribute "cashtags"
     */
    public function testPropertyCashtags()
    {
    }

    /**
     * Test attribute "hashtags"
     */
    public function testPropertyHashtags()
    {
    }

    /**
     * Test attribute "mentions"
     */
    public function testPropertyMentions()
    {
    }

    /**
     * Test attribute "urls"
     */
    public function testPropertyUrls()
    {
    }
}
