<?php
/**
 * TweetPromotedMetricsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.60
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TweetPromotedMetricsTest Class Doc Comment
 *
 * @category    Class
 * @description Promoted nonpublic engagement metrics for the Tweet at the time of the request.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TweetPromotedMetricsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TweetPromotedMetrics"
     */
    public function testTweetPromotedMetrics()
    {
    }

    /**
     * Test attribute "impression_count"
     */
    public function testPropertyImpressionCount()
    {
    }

    /**
     * Test attribute "like_count"
     */
    public function testPropertyLikeCount()
    {
    }

    /**
     * Test attribute "reply_count"
     */
    public function testPropertyReplyCount()
    {
    }

    /**
     * Test attribute "retweet_count"
     */
    public function testPropertyRetweetCount()
    {
    }
}
