<?php
/**
 * TweetNoticeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.60
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TweetNoticeTest Class Doc Comment
 *
 * @category    Class
 * @description TweetNotice
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TweetNoticeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TweetNotice"
     */
    public function testTweetNotice()
    {
    }

    /**
     * Test attribute "application"
     */
    public function testPropertyApplication()
    {
    }

    /**
     * Test attribute "details"
     */
    public function testPropertyDetails()
    {
    }

    /**
     * Test attribute "event_at"
     */
    public function testPropertyEventAt()
    {
    }

    /**
     * Test attribute "event_type"
     */
    public function testPropertyEventType()
    {
    }

    /**
     * Test attribute "extended_details_url"
     */
    public function testPropertyExtendedDetailsUrl()
    {
    }

    /**
     * Test attribute "label_title"
     */
    public function testPropertyLabelTitle()
    {
    }

    /**
     * Test attribute "tweet"
     */
    public function testPropertyTweet()
    {
    }
}
