<?php
/**
 * ListsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.60
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ListsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ListsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getUserListMemberships
     *
     * Get a User's List Memberships.
     *
     */
    public function testGetUserListMemberships()
    {
    }

    /**
     * Test case for listAddMember
     *
     * Add a List member.
     *
     */
    public function testListAddMember()
    {
    }

    /**
     * Test case for listIdCreate
     *
     * Create List.
     *
     */
    public function testListIdCreate()
    {
    }

    /**
     * Test case for listIdDelete
     *
     * Delete List.
     *
     */
    public function testListIdDelete()
    {
    }

    /**
     * Test case for listIdGet
     *
     * List lookup by List ID..
     *
     */
    public function testListIdGet()
    {
    }

    /**
     * Test case for listIdUpdate
     *
     * Update List..
     *
     */
    public function testListIdUpdate()
    {
    }

    /**
     * Test case for listRemoveMember
     *
     * Remove a List member.
     *
     */
    public function testListRemoveMember()
    {
    }

    /**
     * Test case for listUserFollow
     *
     * Follow a List.
     *
     */
    public function testListUserFollow()
    {
    }

    /**
     * Test case for listUserOwnedLists
     *
     * Get a User's Owned Lists..
     *
     */
    public function testListUserOwnedLists()
    {
    }

    /**
     * Test case for listUserPin
     *
     * Pin a List.
     *
     */
    public function testListUserPin()
    {
    }

    /**
     * Test case for listUserPinnedLists
     *
     * Get a User's Pinned Lists.
     *
     */
    public function testListUserPinnedLists()
    {
    }

    /**
     * Test case for listUserUnfollow
     *
     * Unfollow a List.
     *
     */
    public function testListUserUnfollow()
    {
    }

    /**
     * Test case for listUserUnpin
     *
     * Unpin a List.
     *
     */
    public function testListUserUnpin()
    {
    }

    /**
     * Test case for userFollowedLists
     *
     * Get User's Followed Lists.
     *
     */
    public function testUserFollowedLists()
    {
    }
}
