<?php
/**
 * SpacesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.60
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * SpacesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SpacesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for findSpaceById
     *
     * Space lookup by Space ID.
     *
     */
    public function testFindSpaceById()
    {
    }

    /**
     * Test case for findSpacesByCreatorIds
     *
     * Space lookup by their creators.
     *
     */
    public function testFindSpacesByCreatorIds()
    {
    }

    /**
     * Test case for findSpacesByIds
     *
     * Space lookup up Space IDs.
     *
     */
    public function testFindSpacesByIds()
    {
    }

    /**
     * Test case for searchSpaces
     *
     * Search for Spaces.
     *
     */
    public function testSearchSpaces()
    {
    }

    /**
     * Test case for spaceBuyers
     *
     * Retrieve the list of Users who purchased a ticket to the given space.
     *
     */
    public function testSpaceBuyers()
    {
    }

    /**
     * Test case for spaceTweets
     *
     * Retrieve Tweets from a Space..
     *
     */
    public function testSpaceTweets()
    {
    }
}
