<?php
/**
 * TweetsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.60
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * TweetsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TweetsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addOrDeleteRules
     *
     * Add/Delete rules.
     *
     */
    public function testAddOrDeleteRules()
    {
    }

    /**
     * Test case for createTweet
     *
     * Creation of a Tweet.
     *
     */
    public function testCreateTweet()
    {
    }

    /**
     * Test case for deleteTweetById
     *
     * Tweet delete by Tweet ID.
     *
     */
    public function testDeleteTweetById()
    {
    }

    /**
     * Test case for findTweetById
     *
     * Tweet lookup by Tweet ID.
     *
     */
    public function testFindTweetById()
    {
    }

    /**
     * Test case for findTweetsById
     *
     * Tweet lookup by Tweet IDs.
     *
     */
    public function testFindTweetsById()
    {
    }

    /**
     * Test case for findTweetsThatQuoteATweet
     *
     * Retrieve Tweets that quote a Tweet..
     *
     */
    public function testFindTweetsThatQuoteATweet()
    {
    }

    /**
     * Test case for getRules
     *
     * Rules lookup.
     *
     */
    public function testGetRules()
    {
    }

    /**
     * Test case for getTweetsFirehoseStream
     *
     * Firehose stream.
     *
     */
    public function testGetTweetsFirehoseStream()
    {
    }

    /**
     * Test case for getTweetsSample10Stream
     *
     * Sample 10% stream.
     *
     */
    public function testGetTweetsSample10Stream()
    {
    }

    /**
     * Test case for hideReplyById
     *
     * Hide replies.
     *
     */
    public function testHideReplyById()
    {
    }

    /**
     * Test case for listsIdTweets
     *
     * List Tweets timeline by List ID..
     *
     */
    public function testListsIdTweets()
    {
    }

    /**
     * Test case for sampleStream
     *
     * Sample stream.
     *
     */
    public function testSampleStream()
    {
    }

    /**
     * Test case for searchStream
     *
     * Filtered stream.
     *
     */
    public function testSearchStream()
    {
    }

    /**
     * Test case for spaceBuyers
     *
     * Retrieve the list of Users who purchased a ticket to the given space.
     *
     */
    public function testSpaceBuyers()
    {
    }

    /**
     * Test case for spaceTweets
     *
     * Retrieve Tweets from a Space..
     *
     */
    public function testSpaceTweets()
    {
    }

    /**
     * Test case for tweetCountsFullArchiveSearch
     *
     * Full archive search counts.
     *
     */
    public function testTweetCountsFullArchiveSearch()
    {
    }

    /**
     * Test case for tweetCountsRecentSearch
     *
     * Recent search counts.
     *
     */
    public function testTweetCountsRecentSearch()
    {
    }

    /**
     * Test case for tweetsFullarchiveSearch
     *
     * Full-archive search.
     *
     */
    public function testTweetsFullarchiveSearch()
    {
    }

    /**
     * Test case for tweetsRecentSearch
     *
     * Recent search.
     *
     */
    public function testTweetsRecentSearch()
    {
    }

    /**
     * Test case for usersIdLike
     *
     * Causes the User (in the path) to like the specified Tweet.
     *
     */
    public function testUsersIdLike()
    {
    }

    /**
     * Test case for usersIdLikedTweets
     *
     * Returns Tweet objects liked by the provided User ID.
     *
     */
    public function testUsersIdLikedTweets()
    {
    }

    /**
     * Test case for usersIdMentions
     *
     * User mention timeline by User ID.
     *
     */
    public function testUsersIdMentions()
    {
    }

    /**
     * Test case for usersIdRetweets
     *
     * Causes the User (in the path) to retweet the specified Tweet..
     *
     */
    public function testUsersIdRetweets()
    {
    }

    /**
     * Test case for usersIdTimeline
     *
     * User home timeline by User ID.
     *
     */
    public function testUsersIdTimeline()
    {
    }

    /**
     * Test case for usersIdTweets
     *
     * User Tweets timeline by User ID.
     *
     */
    public function testUsersIdTweets()
    {
    }

    /**
     * Test case for usersIdUnlike
     *
     * Causes the User (in the path) to unlike the specified Tweet.
     *
     */
    public function testUsersIdUnlike()
    {
    }

    /**
     * Test case for usersIdUnretweets
     *
     * Causes the User (in the path) to unretweet the specified Tweet.
     *
     */
    public function testUsersIdUnretweets()
    {
    }
}
